apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-api-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/oluwolewilliams/k8s-fastapi-redis-gitops.git
    targetRevision: HEAD
    path: helm/python-api-chart
    helm:
      valueFiles:
        - values-kind.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true