image:
  repository: python-api
  tag: latest
  pullPolicy: Never

ingress:
  enabled: true
  className: nginx
  host: localhost
  path: /api/?(.*)
  pathType: ImplementationSpecific

debugPod:
  enabled: true

redis:
  auth:
    enabled: false