apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cm
  labels:
    {{- include "python-api-chart.labels" . | nindent 4 }}
data:
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}