{{- if .Values.redis.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  labels:
    {{- include "python-api-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
{{- end }}