name: Build, Push and Update Helm (ECR)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      ECR_REPOSITORY: 786359466063.dkr.ecr.us-east-1.amazonaws.com/chancellor4/python-api
      IMAGE_TAG: ${{ github.sha }}

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Build Docker image
      - name: Build image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

      # 5. Push image to ECR
      - name: Push image
        run: |
          docker push $ECR_REPOSITORY:$IMAGE_TAG

      # 6. Update Helm values.yaml
      - name: Update Helm values
        run: |
          sed -i 's|repository:.*|repository: '"$ECR_REPOSITORY"'|' helm/python-api-chart/values.yaml
          sed -i 's|tag:.*|tag: "'"$IMAGE_TAG"'"|' helm/python-api-chart/values.yaml
          sed -i 's|pullPolicy:.*|pullPolicy: Always|' helm/python-api-chart/values.yaml

      # 7. Commit changes back to repo
      - name: Commit Helm image update
        run: |
          git config user.name "github-actions"
          git config user.email "oluwolewilliams3@gmail.com"
          git add helm/python-api-chart/values.yaml
          git commit -m "Update image tag to $IMAGE_TAG" || echo "No changes to commit"
          git push